hydra:
  run:
    dir: ${output_root}/${now:%Y-%m-%d_%H-%M-%S}_grading:${grading}_method:${method_name}_model:${model_name}_site:${site}_fold:${fold_index}_seed:${seed}
output_root: outputs
skip_store: False
root: /home/hoang/data/MOST_OAI_FULL_0_2
meta_root: ./Metadata/in1_outseq_gradingmulti_inter_kl04
pkl_meta_filename: cv_split_5folds_${grading}_oai_evalsite_${site}_${seed}.pkl
log_dir: tb
comment: grading:${grading}_method:${method_name}_model:${model_name}_site:${site}_fold:${fold_index}_seed:${seed}
fold_index: 1
method_name: lstm
model_name: kneeimage
backbone_name: resnet18 #se_resnext50_32x4d
global_pool_name: gap
max_depth: 5
n_pr_classes: 2
n_pn_classes: 5
seq_len: 8
use_bn: True
pretrained: imagenet
pretrained_model: '' #'/home/hoang/workspace/Semix/oaprogression_op/outputs/2020-08-03/22-48-44/snapshots/model_057_max_kappas_0.884.pth'
n_epochs: 500
bs: 32
drop_rate: 0.3
momentum: 0.9
bw: 64
wd: 0
lr: 1e-4
num_workers: 4
grading: KL
subsample_train: -1
snapshots: snapshots
seed: 12345
format: ''
site: B
target_col: first_prog_${grading}
max_ratio: 0.2
oai_meta_filename: OAI_progression_site.csv
most_meta_filename:
gp:
  l0: ''
  l1: ''
  l2: ''
  l3: ''
  l4: 'gap'
# MODEL 2SEQ
n_meta_features: 256
n_img_features: -1
rnn_layer: ${method_name}
rnn_dim: 128
teacher_forcing_ratio: 0.0
drop_rate_between: 0.1
input_3x3: False
embedding_dim: 2048
# OPTIMIZER
clip_norm: -1
beta1: 0.95
beta2: 0.999
# LOSS
progs_coef: 0.0
prognosis_coef: 1.0
kl_coef: 0.0
extract_pr_func: extract_progression_v1
extract_pn_func: extract_prognosis_v1